import Menu from "./componentes/Menu"
const metadata={
  title:'Create Next App',
  desccription:'Generated by create  next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Menu/>
        {children}
      </body>
      <body>
        
      </body>
    </html>
  )
}
